language: rust
rust:
  - 1.12.0
  - stable
  - nightly

matrix:
  include:
  - rust: nightly
    env: FEATURES=unstable

script:
  - cargo build --features="$FEATURES"
  - |
    if [ $TRAVIS_RUST_VERSION == nightly ]; then
      cargo test --features="$FEATURES" &&
      cargo test --features="$FEATURES" -p rayon-core &&
      cargo test --features="$FEATURES" -p rayon-demo
    fi
